FROM nginx:1.29.6-otel

RUN rm /etc/nginx/conf.d/default.conf

COPY static /var/www
COPY nginx/nginx.conf /etc/nginx/nginx.conf
COPY nginx/themes.conf.template /etc/nginx/templates/themes.conf.template

RUN mkdir -p /var/cache/nginx /var/run /var/log/nginx && \
    chown -R nginx:nginx /var/cache/nginx /var/run /var/log/nginx /etc/nginx/conf.d
